### PR TITLE
Upgrade to async-std v1.13

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by la10736** [comment]
Thanks!!!
Anyway, can you explain why you need to bump the `asyc-std` version?

**Comment by jayvdb** [comment]
async-std 0.12 is 2 years old, and has some very old dependencies.

**Comment by EdJoPaTo** [comment]
Saw the release notes and am curious: Why is this relevant? I would expect this to be done automatically by Cargo. Without a lock file the current one will be used and as it's a dev-dependency it's not relevant for the users of rstest as a library. (With the upcoming edition 2024 / resolver 3 it will use the latest one compatible with your current Rust version so its even more helpful to keep the actual required minimal version.)
Am I overlooking something?

**Comment by jayvdb** [comment]
I guess you saw it on https://github.com/la10736/rstest/releases/tag/v0.23.0 , which is automated and exhaustive.

Not on https://github.com/la10736/rstest/blob/master/CHANGELOG.md , which is manually curated.

This PR doesnt impact users much, which is why it would be omitted from `CHANGELOG.md`.

This PR did change the lib docs, so rstest users who copy&paste from the readme/docs would get a modern async-std.  Telling users to depend on async-std v1.5 was really old advice.

**Pull request merged**
