### PR TITLE
refactor: use `core` instead of `std`

### PR DESCRIPTION
**Pull request by rnbguy**
Closes: #282

### CODE REVIEW

**Comment by la10736** [comment]
I don't think we need to change it in all creates but just in `rstest`. The procedural macros ones and the others can still use std.

**Comment by la10736** [comment]
Maybe a little deep look to the rendering module can be useful, but just where it render some code that directly reference `std`

**Comment by la10736** [comment]
What I mean is that just the library crate should be `nostd` bceause it's used by the expanded code. The code in `rstest_macro` crate is executed by the compiler and so can always use `std` library.

Now in `rstest_macros::render` code maybe there is some _quoted_ code that use std path... we should just check it

**Comment by la10736** [comment]
Some examples in `rstest_macros`
- https://github.com/la10736/rstest/blob/master/rstest_macros/src/render/apply_arguments.rs#L121
- https://github.com/la10736/rstest/blob/master/rstest_macros/src/render/fixture.rs#L25-L30
- https://github.com/la10736/rstest/blob/master/rstest_macros/src/render/inject.rs#L113
- https://github.com/la10736/rstest/blob/master/rstest_macros/src/render/mod.rs#L211

**Comment by la10736** [comment]
Moreover a nice to have... end to end test that expose the issue and then is fixed by your code

**Comment by rnbguy** [comment]
I reverted the `core` usage from the old commit. I now use core only in `rstest_macros/src/render` and `rstest/src/magic_conversion`.

I can't make `rstest/src/timeout` no_std compatible -- as it requires `mpsc` and `thread` from `std`.

**Comment by la10736** [comment]
Sorry, I've answered before without put enough brain in it .... sorry.

As I already commented in the linked ticket the library `rstest` can still remain in `std` because it will be linked in an `std` compatible executable. Only the rendered code should use references from `core` instead `std` just because they can be compiled in a library that doesn't have the `std` crate in its namespace.

Anyway in a future I'll remove all references to common code and just reexport them in `rstest` ... this should be the best way

**Comment by rnbguy** [comment]
> the library rstest can still remain in std because it will be linked in an std compatible executable.

Gotcha! I reverted the changes in `rstest` crate. the changes are only in `rstest_macros` crate at the generate codes.

**Review by la10736 — CHANGES_REQUESTED** [review]
Can you fill che changelog file and try to add an e2e test... Let me know if you need any hael for the e2e stuff

**Comment by la10736** [comment]
Ok, I merge it. But I'll add at least a e2e test before publish it

**Comment by rnbguy** [comment]
Hey, many thanks for merging this. Sorry, I couldn't get some time to add the changelog entry and the e2e test.

**Comment by la10736** [comment]
I did it... Thanks again

Il giorno dom 17 nov 2024 alle ore 15:50 Rano | Ranadeep <
***@***.***> ha scritto:

**Pull request merged**
