### PR TITLE
replace futures with futures-util

### PR DESCRIPTION
**Pull request by mati865**
This slightly reduces depedency tree.

### CODE REVIEW

**Review by la10736 — COMMENTED** [review]
Seams that this change broke the msrv test :cry:

We should go little bit deeper to understand what's happen and if is possible to leave the same msrv or we should bump it

**Comment by mati865** [comment]
The failure is unrelated. `futures` crate pulls in `futures-util` anyway, so the only thing that changes here is using code directly instead of reexport from `futures`. I'm pretty sure any PR would fail like that.

I don't know this test setup, but to me it looks like toolchain in version 1.83 has generated lockfile in version 4 (this is the new default), but version 4 is supported only by toolchains 1,78+.

**Comment by la10736** [comment]
> The failure is unrelated. `futures` crate pulls in `futures-util` anyway, so the only thing that changes here is using code directly instead of reexport from `futures`. I'm pretty sure any PR would fail like that.
> 
> I don't know this test setup, but to me it looks like toolchain in version 1.83 has generated lockfile in version 4 (this is the new default), but version 4 is supported only by toolchains 1,78+.

Maybe you're right. Yesterday it was midnight and I was too tired to check msrv on main branch: I just trusted the weakly CI... But there is something wired here: the weakly CI was run 3 days ago and didn't find any issues.

Now I run again the CI on main to check if there is something new.

**Comment by la10736** [comment]
> 
> Now I run again the CI on main to check if there is something new.

Ok, now the CI is failed also in main in the same way. I guess that a new cargo hack version was released in these days.

I can merge this PR because the issue is un related

**Review by la10736 — APPROVED** [review]
Thanks

LGTM

**Comment by mati865** [comment]
No worries, thanks for the quick response.

**Comment by mati865** [comment]
> I don't know this test setup, but to me it looks like toolchain in version 1.83 has generated lockfile in version 4 (this is the new default), but version 4 is supported only by toolchains 1,78+.

I've made a quick look at I'm certain this is the case. Pinning the toolchain in MSRV job to anything lower than 1.83 will avoid the problem.

**Pull request merged**
